wow_news:
    resource: "@WowNewsBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

# FOSUser Bundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#EasyAdminBundle
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

