<?php

namespace WowNewsBundle\Repository;

/**
 * CommentariesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentariesRepository extends \Doctrine\ORM\EntityRepository
{
}
